//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ActionLog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ActionLog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ActionLog", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Log.
        /// </summary>
        internal static string lblActionLog {
            get {
                return ResourceManager.GetString("lblActionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Log List.
        /// </summary>
        internal static string lblActionLogList {
            get {
                return ResourceManager.GetString("lblActionLogList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string lblClose {
            get {
                return ResourceManager.GetString("lblClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Object.
        /// </summary>
        internal static string lblGvHdrActionObject {
            get {
                return ResourceManager.GetString("lblGvHdrActionObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string lblGvHdrActionPerformedOn {
            get {
                return ResourceManager.GetString("lblGvHdrActionPerformedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Type.
        /// </summary>
        internal static string lblGvHdrActionType {
            get {
                return ResourceManager.GetString("lblGvHdrActionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Name.
        /// </summary>
        internal static string lblGvHdrColumnName {
            get {
                return ResourceManager.GetString("lblGvHdrColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string lblGvHdrUser {
            get {
                return ResourceManager.GetString("lblGvHdrUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string lblGvHdrView {
            get {
                return ResourceManager.GetString("lblGvHdrView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Log.
        /// </summary>
        internal static string lblHeaderGvMsg {
            get {
                return ResourceManager.GetString("lblHeaderGvMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTION LOG.
        /// </summary>
        internal static string lblMainHeader {
            get {
                return ResourceManager.GetString("lblMainHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string lblSearchActionDate {
            get {
                return ResourceManager.GetString("lblSearchActionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Object.
        /// </summary>
        internal static string lblSearchActionObject {
            get {
                return ResourceManager.GetString("lblSearchActionObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Type.
        /// </summary>
        internal static string lblSearchActionType {
            get {
                return ResourceManager.GetString("lblSearchActionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string lblSearchUserName {
            get {
                return ResourceManager.GetString("lblSearchUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Value.
        /// </summary>
        internal static string litGvHdrNewData {
            get {
                return ResourceManager.GetString("litGvHdrNewData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Value.
        /// </summary>
        internal static string litGvHdrOldData {
            get {
                return ResourceManager.GetString("litGvHdrOldData", resourceCulture);
            }
        }
    }
}
