//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Deposits {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Deposits() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Deposits", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        internal static string lblDeposit {
            get {
                return ResourceManager.GetString("lblDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        internal static string lblDepositAccountName {
            get {
                return ResourceManager.GetString("lblDepositAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string lblDepositAmount {
            get {
                return ResourceManager.GetString("lblDepositAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Name.
        /// </summary>
        internal static string lblDepositeName {
            get {
                return ResourceManager.GetString("lblDepositeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEPOSIT SETUP.
        /// </summary>
        internal static string lblDepositInputHeader {
            get {
                return ResourceManager.GetString("lblDepositInputHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit List.
        /// </summary>
        internal static string lblDepositList {
            get {
                return ResourceManager.GetString("lblDepositList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Name.
        /// </summary>
        internal static string lblDepositName {
            get {
                return ResourceManager.GetString("lblDepositName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit No.
        /// </summary>
        internal static string lblDepositNo {
            get {
                return ResourceManager.GetString("lblDepositNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string lblGvHdrDepositAmount {
            get {
                return ResourceManager.GetString("lblGvHdrDepositAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Name.
        /// </summary>
        internal static string lblGvHdrDepositName {
            get {
                return ResourceManager.GetString("lblGvHdrDepositName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit No.
        /// </summary>
        internal static string lblGvHdrlDepositNo {
            get {
                return ResourceManager.GetString("lblGvHdrlDepositNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        internal static string lblHeaderConfirmDeletePopup {
            get {
                return ResourceManager.GetString("lblHeaderConfirmDeletePopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEPOSIT.
        /// </summary>
        internal static string lblMainHeader {
            get {
                return ResourceManager.GetString("lblMainHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage should be less than or equal to 100..
        /// </summary>
        internal static string lblMsgDepositMarginLimitInPercentage {
            get {
                return ResourceManager.GetString("lblMsgDepositMarginLimitInPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        internal static string lblSDepositName {
            get {
                return ResourceManager.GetString("lblSDepositName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit List.
        /// </summary>
        internal static string lblStatutoryList {
            get {
                return ResourceManager.GetString("lblStatutoryList", resourceCulture);
            }
        }
    }
}
