//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InfillSetup {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InfillSetup() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.InfillSetup", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        internal static string btnAddBottomDenomination {
            get {
                return ResourceManager.GetString("btnAddBottomDenomination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        internal static string btnAddTopDenomination {
            get {
                return ResourceManager.GetString("btnAddTopDenomination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Exit.
        /// </summary>
        internal static string btnSaveAndExit {
            get {
                return ResourceManager.GetString("btnSaveAndExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LabelName.
        /// </summary>
        internal static string ddlLabelName {
            get {
                return ResourceManager.GetString("ddlLabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No any record found..
        /// </summary>
        internal static string lblNoRecordFound {
            get {
                return ResourceManager.GetString("lblNoRecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string litGvfViewDelete {
            get {
                return ResourceManager.GetString("litGvfViewDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string litGvrNo {
            get {
                return ResourceManager.GetString("litGvrNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BG. Color.
        /// </summary>
        internal static string ltrBackgroundColor {
            get {
                return ResourceManager.GetString("ltrBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Color.
        /// </summary>
        internal static string ltrFontColor {
            get {
                return ResourceManager.GetString("ltrFontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infill Name.
        /// </summary>
        internal static string ltrGvrInfillName {
            get {
                return ResourceManager.GetString("ltrGvrInfillName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Name.
        /// </summary>
        internal static string ltrGvrLabelName {
            get {
                return ResourceManager.GetString("ltrGvrLabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infill Name.
        /// </summary>
        internal static string ltrInfill {
            get {
                return ResourceManager.GetString("ltrInfill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infill Code.
        /// </summary>
        internal static string ltrInfillCode {
            get {
                return ResourceManager.GetString("ltrInfillCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infill Setup.
        /// </summary>
        internal static string ltrInfillHeading {
            get {
                return ResourceManager.GetString("ltrInfillHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infill Name.
        /// </summary>
        internal static string ltrInfillName {
            get {
                return ResourceManager.GetString("ltrInfillName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Name.
        /// </summary>
        internal static string ltrLabelName {
            get {
                return ResourceManager.GetString("ltrLabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFILL SETUP.
        /// </summary>
        internal static string ltrMainHeading {
            get {
                return ResourceManager.GetString("ltrMainHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Name.
        /// </summary>
        internal static string ltrName {
            get {
                return ResourceManager.GetString("ltrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Area.
        /// </summary>
        internal static string ltrSearchArea {
            get {
                return ResourceManager.GetString("ltrSearchArea", resourceCulture);
            }
        }
    }
}
