//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CompanySetup {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompanySetup() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CompanySetup", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same as Registered Address.
        /// </summary>
        internal static string lblAsPermanenetAddress {
            get {
                return ResourceManager.GetString("lblAsPermanenetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Domain.
        /// </summary>
        internal static string lblBusinessDomain {
            get {
                return ResourceManager.GetString("lblBusinessDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Code.
        /// </summary>
        internal static string lblCompanyCode {
            get {
                return ResourceManager.GetString("lblCompanyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Logo.
        /// </summary>
        internal static string lblCompanyLogo {
            get {
                return ResourceManager.GetString("lblCompanyLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string lblCompanyName {
            get {
                return ResourceManager.GetString("lblCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Type.
        /// </summary>
        internal static string lblCompanyType {
            get {
                return ResourceManager.GetString("lblCompanyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact No.
        /// </summary>
        internal static string lblContactNo {
            get {
                return ResourceManager.GetString("lblContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        internal static string lblDisplayName {
            get {
                return ResourceManager.GetString("lblDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string lblFax {
            get {
                return ResourceManager.GetString("lblFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Name.
        /// </summary>
        internal static string lblGvHdrDocumentName {
            get {
                return ResourceManager.GetString("lblGvHdrDocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string lblGvHdrFile {
            get {
                return ResourceManager.GetString("lblGvHdrFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string lblGvHdrNumber {
            get {
                return ResourceManager.GetString("lblGvHdrNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string lblHeaderAddressInformation {
            get {
                return ResourceManager.GetString("lblHeaderAddressInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image / Company Logo.
        /// </summary>
        internal static string lblHeaderCompanyLogo {
            get {
                return ResourceManager.GetString("lblHeaderCompanyLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statutory Registration.
        /// </summary>
        internal static string lblHeaderStatutoryRegistration {
            get {
                return ResourceManager.GetString("lblHeaderStatutoryRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPANY SETUP.
        /// </summary>
        internal static string lblMainHeader {
            get {
                return ResourceManager.GetString("lblMainHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record with same email already exists..
        /// </summary>
        internal static string lblMsgDuplicateEmail {
            get {
                return ResourceManager.GetString("lblMsgDuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo removed successfully..
        /// </summary>
        internal static string lblMsgLogoRemoved {
            get {
                return ResourceManager.GetString("lblMsgLogoRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Office.
        /// </summary>
        internal static string lblOfficeAddress {
            get {
                return ResourceManager.GetString("lblOfficeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .jpg|.JPG|.jpeg|.JPEG|.png|.PNG|gif|GIF|.bmp|.BMP.
        /// </summary>
        internal static string lblPhotoUploadTooltip {
            get {
                return ResourceManager.GetString("lblPhotoUploadTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Office.
        /// </summary>
        internal static string lblRegisteredAddress {
            get {
                return ResourceManager.GetString("lblRegisteredAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statutory List.
        /// </summary>
        internal static string lblStatutoryList {
            get {
                return ResourceManager.GetString("lblStatutoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string lblURL {
            get {
                return ResourceManager.GetString("lblURL", resourceCulture);
            }
        }
    }
}
