//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CounterName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CounterName() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CounterName", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter No..
        /// </summary>
        internal static string lblCounterName {
            get {
                return ResourceManager.GetString("lblCounterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter No. List.
        /// </summary>
        internal static string lblCounterNameList {
            get {
                return ResourceManager.GetString("lblCounterNameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter No..
        /// </summary>
        internal static string lblGvHdrCounterNo {
            get {
                return ResourceManager.GetString("lblGvHdrCounterNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter No..
        /// </summary>
        internal static string lblHeaderConfirmDeletePopup {
            get {
                return ResourceManager.GetString("lblHeaderConfirmDeletePopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter No..
        /// </summary>
        internal static string lblHeaderPopupCounterName {
            get {
                return ResourceManager.GetString("lblHeaderPopupCounterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUNTER SETUP.
        /// </summary>
        internal static string lblMainHeader {
            get {
                return ResourceManager.GetString("lblMainHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter No..
        /// </summary>
        internal static string lblSearchCounterName {
            get {
                return ResourceManager.GetString("lblSearchCounterName", resourceCulture);
            }
        }
    }
}
