//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQT.Symphony.UI.Web.FrontDesk.SrvcRefInvestorList {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SrvcRefInvestorList.InvestorListSoap")]
    public interface InvestorListSoap {
        
        // CODEGEN: Parameter 'InvestorID' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInvestorListInDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SQT.Symphony.UI.Web.FrontDesk.SrvcRefInvestorList.GetInvestorListInDataSetResponse GetInvestorListInDataSet(SQT.Symphony.UI.Web.FrontDesk.SrvcRefInvestorList.GetInvestorListInDataSetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVoucherListByInvestorIDInDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetVoucherListByInvestorIDInDataSet(System.Guid InvestorID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVoucherDetailByVoucherID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetVoucherDetailByVoucherID(System.Guid ResVoucherID);
        
        // CODEGEN: Parameter 'AllocatedRoomID' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_ReservationAndAllocatedRoomID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SQT.Symphony.UI.Web.FrontDesk.SrvcRefInvestorList.Update_ReservationAndAllocatedRoomIDResponse Update_ReservationAndAllocatedRoomID(SQT.Symphony.UI.Web.FrontDesk.SrvcRefInvestorList.Update_ReservationAndAllocatedRoomIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInvestorEmailAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetInvestorEmailAddress();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInvestorListInDataSet", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetInvestorListInDataSetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> InvestorID;
        
        public GetInvestorListInDataSetRequest() {
        }
        
        public GetInvestorListInDataSetRequest(System.Nullable<System.Guid> InvestorID) {
            this.InvestorID = InvestorID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInvestorListInDataSetResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetInvestorListInDataSetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet GetInvestorListInDataSetResult;
        
        public GetInvestorListInDataSetResponse() {
        }
        
        public GetInvestorListInDataSetResponse(System.Data.DataSet GetInvestorListInDataSetResult) {
            this.GetInvestorListInDataSetResult = GetInvestorListInDataSetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_ReservationAndAllocatedRoomID", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Update_ReservationAndAllocatedRoomIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid ResVoucherID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Guid ReservationID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> AllocatedRoomID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string UpdateMode;
        
        public Update_ReservationAndAllocatedRoomIDRequest() {
        }
        
        public Update_ReservationAndAllocatedRoomIDRequest(System.Guid ResVoucherID, System.Guid ReservationID, System.Nullable<System.Guid> AllocatedRoomID, string UpdateMode) {
            this.ResVoucherID = ResVoucherID;
            this.ReservationID = ReservationID;
            this.AllocatedRoomID = AllocatedRoomID;
            this.UpdateMode = UpdateMode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_ReservationAndAllocatedRoomIDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Update_ReservationAndAllocatedRoomIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Update_ReservationAndAllocatedRoomIDResult;
        
        public Update_ReservationAndAllocatedRoomIDResponse() {
        }
        
        public Update_ReservationAndAllocatedRoomIDResponse(bool Update_ReservationAndAllocatedRoomIDResult) {
            this.Update_ReservationAndAllocatedRoomIDResult = Update_ReservationAndAllocatedRoomIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InvestorListSoapChannel : SQT.Symphony.UI.Web.FrontDesk.SrvcRefInvestorList.InvestorListSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InvestorListSoapClient : System.ServiceModel.ClientBase<SQT.Symphony.UI.Web.FrontDesk.SrvcRefInvestorList.InvestorListSoap>, SQT.Symphony.UI.Web.FrontDesk.SrvcRefInvestorList.InvestorListSoap {
        
        public InvestorListSoapClient() {
        }
        
        public InvestorListSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InvestorListSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvestorListSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvestorListSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SQT.Symphony.UI.Web.FrontDesk.SrvcRefInvestorList.GetInvestorListInDataSetResponse SQT.Symphony.UI.Web.FrontDesk.SrvcRefInvestorList.InvestorListSoap.GetInvestorListInDataSet(SQT.Symphony.UI.Web.FrontDesk.SrvcRefInvestorList.GetInvestorListInDataSetRequest request) {
            return base.Channel.GetInvestorListInDataSet(request);
        }
        
        public System.Data.DataSet GetInvestorListInDataSet(System.Nullable<System.Guid> InvestorID) {
            SQT.Symphony.UI.Web.FrontDesk.SrvcRefInvestorList.GetInvestorListInDataSetRequest inValue = new SQT.Symphony.UI.Web.FrontDesk.SrvcRefInvestorList.GetInvestorListInDataSetRequest();
            inValue.InvestorID = InvestorID;
            SQT.Symphony.UI.Web.FrontDesk.SrvcRefInvestorList.GetInvestorListInDataSetResponse retVal = ((SQT.Symphony.UI.Web.FrontDesk.SrvcRefInvestorList.InvestorListSoap)(this)).GetInvestorListInDataSet(inValue);
            return retVal.GetInvestorListInDataSetResult;
        }
        
        public System.Data.DataSet GetVoucherListByInvestorIDInDataSet(System.Guid InvestorID) {
            return base.Channel.GetVoucherListByInvestorIDInDataSet(InvestorID);
        }
        
        public System.Data.DataSet GetVoucherDetailByVoucherID(System.Guid ResVoucherID) {
            return base.Channel.GetVoucherDetailByVoucherID(ResVoucherID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SQT.Symphony.UI.Web.FrontDesk.SrvcRefInvestorList.Update_ReservationAndAllocatedRoomIDResponse SQT.Symphony.UI.Web.FrontDesk.SrvcRefInvestorList.InvestorListSoap.Update_ReservationAndAllocatedRoomID(SQT.Symphony.UI.Web.FrontDesk.SrvcRefInvestorList.Update_ReservationAndAllocatedRoomIDRequest request) {
            return base.Channel.Update_ReservationAndAllocatedRoomID(request);
        }
        
        public bool Update_ReservationAndAllocatedRoomID(System.Guid ResVoucherID, System.Guid ReservationID, System.Nullable<System.Guid> AllocatedRoomID, string UpdateMode) {
            SQT.Symphony.UI.Web.FrontDesk.SrvcRefInvestorList.Update_ReservationAndAllocatedRoomIDRequest inValue = new SQT.Symphony.UI.Web.FrontDesk.SrvcRefInvestorList.Update_ReservationAndAllocatedRoomIDRequest();
            inValue.ResVoucherID = ResVoucherID;
            inValue.ReservationID = ReservationID;
            inValue.AllocatedRoomID = AllocatedRoomID;
            inValue.UpdateMode = UpdateMode;
            SQT.Symphony.UI.Web.FrontDesk.SrvcRefInvestorList.Update_ReservationAndAllocatedRoomIDResponse retVal = ((SQT.Symphony.UI.Web.FrontDesk.SrvcRefInvestorList.InvestorListSoap)(this)).Update_ReservationAndAllocatedRoomID(inValue);
            return retVal.Update_ReservationAndAllocatedRoomIDResult;
        }
        
        public System.Data.DataSet GetInvestorEmailAddress() {
            return base.Channel.GetInvestorEmailAddress();
        }
    }
}
