//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQT.Symphony.UI.Web.IRMS.Applications.DashBoard {
    
    
    public partial class DashBoardInvestors {
        
        /// <summary>
        /// CltrDashBoardInvestors1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SQT.Symphony.UI.Web.IRMS.UIControls.DashBoard.CltrDashBoardInvestors CltrDashBoardInvestors1;
    }
}
