CREATE TABLE mst_partner
(
	[PartnerID]				CHAR(38)			NOT NULL PRIMARY KEY,
	[FirstName]				VARCHAR(61)			NULL DEFAULT NULL,
	[MiddleName]			VARCHAR(61)			NULL DEFAULT NULL,
	[LastName]				VARCHAR(61)			NULL DEFAULT NULL,
	[DisplayName]			VARCHAR(183)		NULL DEFAULT NULL,
	[MobileNo]				VARCHAR(13)			NULL DEFAULT NULL,
	[Email]					VARCHAR(161)		NULL DEFAULT NULL,
	[Address]				VARCHAR(161)		NULL DEFAULT NULL,
	[PhotoImage]			VARCHAR(361)		NULL DEFAULT NULL,
	[CreatedOn]				DATETIME			NULL DEFAULT NULL,
	[CreatedBy]				CHAR(38)			NULL DEFAULT NULL,
	[UpdatedOn]				DATETIME			NULL DEFAULT NULL,
	[UpdatedBy]				CHAR(38)			NULL DEFAULT NULL,
	[TotalProperties]		INT					NULL DEFAULT NULL,
	[TotalInvestment]		DECIMAL(18,2)		NULL DEFAULT NULL,
	[IsActive]				BIT					NULL DEFAULT NULL,
	[UpdateLog]				TIMESTAMP			NULL DEFAULT NULL,
	[SeqNo]					INT					NULL DEFAULT NULL	
)
GO