CREATE TABLE dbo.tra_propertypayment
(
	[PropertyPaymentID]			UNIQUEIDENTIFIER	NOT NULL PRIMARY KEY,
	[PropertyID]				UNIQUEIDENTIFIER	NULL DEFAULT NULL,
	[PropertyScheduleID]		UNIQUEIDENTIFIER	NULL DEFAULT NULL,
	[AmountPaid]				DECIMAL(18,2)		NULL DEFAULT NULL,	
	[MOPTerm]					VARCHAR(37)			NULL DEFAULT NULL,
	[DateOfTransaction]			DATETIME			NULL DEFAULT NULL,
	[BankName]					VARCHAR(161)		NULL DEFAULT NULL,
	[ChequeNo]					VARCHAR(11)			NULL DEFAULT NULL,
	[ChequeTo]					VARCHAR(161)		NULL DEFAULT NULL,
	[OrderNo]					INT					IDENTITY(1,1) NOT NULL,
	[UserID]					CHAR(38)			NULL DEFAULT NULL,
	[Description]				VARCHAR(3710)		NULL DEFAULT NULL
)
GO