CREATE TABLE dbo.tra_partnerpayment
(
	[PartnerPaymentID]				UNIQUEIDENTIFIER	NOT NULL PRIMARY KEY,
	[PartnerID]						UNIQUEIDENTIFIER	NULL DEFAULT NULL,
	[PropertyID]					UNIQUEIDENTIFIER	NULL DEFAULT NULL,
	[PropertyPurchaseScheduleID]	UNIQUEIDENTIFIER	NULL DEFAULT NULL,
	[PaymentAmount]					DECIMAL(18,2)		NULL DEFAULT NULL,
	[MOPTerm]						VARCHAR(39)			NULL DEFAULT NULL,
	[BankName]						VARCHAR(61)			NULL DEFAULT NULL,
	[ChequeNo]						VARCHAR(11)			NULL DEFAULT NULL,
	[TransactionDate]				DATETIME			NULL DEFAULT NULL,
	[ReceivedBy]					CHAR(38)			NULL DEFAULT NULL,
	[SeqNo]							INT					IDENTITY(1,1) NOT NULL,
	[IsActive]						BIT					NULL DEFAULT NULL,
	[UpdateLog]						DATETIME			NULL DEFAULT NULL,
	[UploadDocument]				VARCHAR(361)		NULL DEFAULT NULL,
	[Description]					VARCHAR(3710)		NULL DEFAULT NULL
)
GO