CREATE TABLE tra_partnerpayment
(
	[PartnerPaymentID]		CHAR(38)		NOT NULL PRIMARY KEY,
	[PartnerID]				CHAR(38)		NULL DEFAULT NULL,
	[PropertyID]			CHAR(38)		NULL DEFAULT NULL,
	[PropertyScheduleID]	CHAR(38)		NULL DEFAULT NULL,
	[PaymentAmount]			DECIMAL(18,2)	NULL DEFAULT NULL,
	[MOPTerm]				VARCHAR(39)		NULL DEFAULT NULL,
	[BankName]				VARCHAR(61)		NULL DEFAULT NULL,
	[ChequeNo]				VARCHAR(11)		NULL DEFAULT NULL,
	[TransactionDate]		DATETIME		NULL DEFAULT NULL,
	[ReceivedBy]			CHAR(38)		NULL DEFAULT NULL,
	[SeqNo]					INT				NULL DEFAULT NULL,
	[IsActive]				BIT				NULL DEFAULT NULL,
	[UpdateLog]				DATETIME		NULL DEFAULT NULL,
	[UploadDocument]		VARCHAR(361)	NULL DEFAULT NULL,
	[Description]			VARCHAR(3710)	NULL DEFAULT NULL
)
GO